name: badgify
description: "Badgify Frontend"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.0.5

  nb_utils: ^7.0.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5

  # FIREBASE
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.0
  firebase_auth: ^4.19.3
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0

  # FIREBASE MESSAGING
  firebase_messaging: ^14.8.0
  flutter_local_notifications: ^17.0.0

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #google
  google_sign_in: ^6.2.1

  #apple
  the_apple_sign_in: ^1.1.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/badgify_logo_long.png
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
